# This is a basic workflow to help you get started with Actions

name: CI mit Artifakte

# Controls when the workflow will run
on:
  # Triggers the workflow on push develop or tag or pull request events
  push:
    branches:
      - main
      - develop
      - feature*
      - release*
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Prepare Build
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --yes coreutils p7zip-full qemu-user-static
        sudo pip list
        pip list